name: release

on:
  release:
    types:
    - published
    - unpublished
    - deleted

defaults:
  run:
    shell: pwsh

env:
  TAG_NAME: ${{ github.event.release.tag_name }}
  POWERSHELLGALLERY_KEY: ${{ secrets.POWERSHELLGALLERY_KEY }}

jobs:
  preflight:
    if: ${{ github.event.action == 'published' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify module version
        run: |
          $Version = $env:TAG_NAME -replace '^v'
          $Manifest = Test-ModuleManifest .\powershell-devops.psd1
          if ($Version -ne $Manifest.Version) {
            throw "The module version '$($Manifest.Version)' does not match the release version '$Version'."
          }

  publish:
    if: ${{ github.event.action == 'published' }}
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish to PowerShellGallery
        run: |
          $Version = $env:TAG_NAME -replace '^v'
          if (Find-Module powershell-devops -RequiredVersion $Version -ErrorAction SilentlyContinue) {
            Write-Host "Relisting version: $Version"
            Invoke-RestMethod `
              https://www.powershellgallery.com/api/v2/package/powershell-devops/$Version `
              -Method POST `
              -Headers @{'X-NuGet-ApiKey' = $env:POWERSHELLGALLERY_KEY}
          } else {
            Write-Host "Publishing version: $Version"
            Publish-Module -Path .\ -NuGetApiKey $env:POWERSHELLGALLERY_KEY
          }

  unlist:
    if: ${{ github.event.action == 'unpublished' || github.event.action == 'deleted' }}
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          $Version = $env:TAG_NAME -replace '^v'
          Write-Host "Unlisting version: $Version"
          Invoke-RestMethod `
            https://www.powershellgallery.com/api/v2/package/powershell-devops/$Version `
            -Method DELETE `
            -Headers @{'X-NuGet-ApiKey' = $env:POWERSHELLGALLERY_KEY}