name: release

on:
  release:
    types:
    - published
    - unpublished
    - deleted

defaults:
  run:
    shell: pwsh

env:
  RELEASE_ID: ${{ github.event.release.id }}
  TAG_NAME: ${{ github.event.release.tag_name }}
  POWERSHELLGALLERY_KEY: ${{ secrets.POWERSHELLGALLERY_KEY }}

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: smokedlinq/powershell-devops@v0

      - id: verify
        name: Verify module version
        run: ./.github/workflows/scripts/verify.ps1

  publish:
    if: ${{ github.event.action == 'published' }}
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: smokedlinq/powershell-devops@v0

      - name: Publish to PowerShellGallery
        run: ./.github/workflows/scripts/publish.ps1

      - name: Update major version tag
        if: ${{ env.MAJOR_TAG_NAME != '' }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ env.MAJOR_TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unlist:
    if: ${{ github.event.action == 'unpublished' || github.event.action == 'deleted' }}
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: smokedlinq/powershell-devops@v0

      - name: Unlist from PowerShellGallery
        run: ./.github/workflows/scripts/unlist.ps1